stages:
  - build
  - test
  - security_scan

variables:
  IMAGE_BACKEND: "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA"
  IMAGE_FRONTEND: "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA"

build:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_BACKEND ./backend
    - docker push $IMAGE_BACKEND
    - docker build -t $IMAGE_FRONTEND ./frontend
    - docker push $IMAGE_FRONTEND

test:
  stage: test
  image: node:18-alpine
  script:
    - cd backend
    - npm ci
    - npm test

security_scan:
  stage: security_scan
  image: aquasec/trivy:latest
  script:
    - trivy image --severity CRITICAL --exit-code 1 --no-progress $IMAGE_BACKEND